// Dados por cultura — peso da saca (kg), ciclo médio (dias), umidade padrão (%), impureza padrão (%)
export const CULTURAS = {
  soja: {
    nome: 'Soja',
    pesoSaca: 60,
    cicloMedio: 120,
    variedades: {
      precoce: { ciclo: 100 },
      medio: { ciclo: 120 },
      tardio: { ciclo: 140 },
    },
    umidadePadrao: 14,
    impurezaPadrao: 1,
    fatorUmidade: 1.0,
    fatorImpureza: 1.0,
  },
  milho: {
    nome: 'Milho',
    pesoSaca: 60,
    cicloMedio: 130,
    variedades: {
      precoce: { ciclo: 110 },
      medio: { ciclo: 130 },
      safrinha: { ciclo: 120 },
    },
    umidadePadrao: 14,
    impurezaPadrao: 1,
    fatorUmidade: 1.0,
    fatorImpureza: 1.0,
  },
  trigo: {
    nome: 'Trigo',
    pesoSaca: 60,
    cicloMedio: 120,
    variedades: {
      precoce: { ciclo: 100 },
      medio: { ciclo: 120 },
    },
    umidadePadrao: 13,
    impurezaPadrao: 1,
    fatorUmidade: 1.0,
    fatorImpureza: 1.0,
  },
  cafe: {
    nome: 'Café',
    pesoSaca: 60,
    cicloMedio: 365,
    variedades: {},
    umidadePadrao: 12,
    impurezaPadrao: 1,
    fatorUmidade: 1.0,
    fatorImpureza: 1.0,
  },
  algodao: {
    nome: 'Algodão',
    pesoSaca: 20.42,
    cicloMedio: 180,
    variedades: {},
    umidadePadrao: 12,
    impurezaPadrao: 2,
    fatorUmidade: 1.0,
    fatorImpureza: 1.0,
  },
  arroz: {
    nome: 'Arroz',
    pesoSaca: 60,
    cicloMedio: 130,
    variedades: {
      precoce: { ciclo: 100 },
      medio: { ciclo: 130 },
    },
    umidadePadrao: 13,
    impurezaPadrao: 1,
    fatorUmidade: 1.0,
    fatorImpureza: 1.0,
  },
  feijao: {
    nome: 'Feijão',
    pesoSaca: 60,
    cicloMedio: 90,
    variedades: {
      precoce: { ciclo: 75 },
      medio: { ciclo: 90 },
    },
    umidadePadrao: 14,
    impurezaPadrao: 1,
    fatorUmidade: 1.0,
    fatorImpureza: 1.0,
  },
  sorgo: {
    nome: 'Sorgo',
    pesoSaca: 60,
    cicloMedio: 110,
    variedades: {},
    umidadePadrao: 14,
    impurezaPadrao: 1,
    fatorUmidade: 1.0,
    fatorImpureza: 1.0,
  },
};
